version: "3.8"
services:
  app:
    image: "${DOCKER_IMAGE:-corpusops/bitwardentools}"
    build:
      context: "."
      args:
        PY_VER: "3.12"
        REQUIREMENTS: requirements/requirements.txt requirements/requirements-dev.txt
    environment:
      START_COMMAND: "${START_COMMAND:-while true;do echo sleep;sleep 65534;done}"
    volumes:
    - "${DATA_FOLDER:-./data}:/w/data"
    env_file: [.env, .env.local]
