version: "3.8"
services:
  app:
    image: "junkydeveloper/vaultwardentools"
    build:
      context: "."
      args:
        PY_VER: "3.12"
        REQUIREMENTS: requirements/requirements.txt requirements/requirements-dev.txt
